version: '3'
services:
  face-auth:
    image: anirbankar21/faceauth_face-auth-django
    build: FaceRecogEngine/
    depends_on:
      - model-server
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./FaceRecogEngine/:/app
    ports:
      - "80:8000"
    links: 
      - "model-server:face-recog-model-server"
  model-server:
    image: anirbankar21/faceauth_model-server
    command: tensorflow_model_server --port=8500 --rest_api_port=8501 --model_name=${MODEL_NAME} --model_base_path=${MODEL_BASE_PATH}/${MODEL_NAME}
    volumes:
      - ./FaceRecogModelServer/:/app
    ports:
      - "8500:8500"
      - "8501:8501"