version: '3'
services:
  serve:
    build: .
    command: tensorflow_model_server --port=8500 --rest_api_port=8501 --model_name=${MODEL_NAME} --model_base_path=${MODEL_BASE_PATH}/${MODEL_NAME}
    volumes:
      - .:/app
    ports:
      - "8500:8500"
      - "8501:8501"